import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import SubNav from "@/components/layout/subnav";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-200 flex flex-col ">
            <div className="sticky top-0 z-50 ">
              <Header />
              <SubNav />
            </div>
            <main className="flex flex-col grow">{children}</main>
            <Footer />
        </div>
      </body>
    </html>
  );
}
